dic = [{'id': 'in69jje',
  'Nombre': 'Katia Michel Martinez Rios',
  'Boleta': 2014601112,
  'Correo': 'kmartinezr1303@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 7},
 {'id': 'inl2dtj',
  'Nombre': 'César Armando Martínez Cedillo',
  'Boleta': 2014130781,
  'Correo': 'cmartinezc1300@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 7},
 {'id': 'in1ui2w',
  'Nombre': 'Rodolfo Carlos Lagunas Jardines ',
  'Boleta': 2020330309,
  'Correo': 'rlagunasj1900@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'in5dx3x',
  'Nombre': 'Rodrigo Torres Castillo',
  'Boleta': 2019330360,
  'Correo': 'rtorresc1500@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 5},
 {'id': 'ineids2',
  'Nombre': 'Antonio Elias Vargas ',
  'Boleta': 2020330046,
  'Correo': 'aeliasv1600@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'inmczzw',
  'Nombre': 'Cristian Ramírez García',
  'Boleta': 2018331441,
  'Correo': 'cramirezg1702@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 4},
 {'id': 'inzyeox',
  'Nombre': 'Angel Alavez Dávila ',
  'Boleta': 2019630212,
  'Correo': 'aalavezd1500@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'in2w6hx',
  'Nombre': 'David Fragoso Vega',
  'Boleta': 2015080399,
  'Correo': 'dfragosov1400@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 4},
 {'id': 'inq2ukk',
  'Nombre': 'Francisco Javier Torres Galicia',
  'Boleta': 2015330317,
  'Correo': 'ftorresg1400@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 9},
 {'id': 'in2rkeu',
  'Nombre': 'Luis Enrique Patiño Quiroz ',
  'Boleta': 2016601297,
  'Correo': 'lpatinoq1500@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 8},
 {'id': 'iny7mz5',
  'Nombre': 'Erwin Eduardo Guerrero Cazares ',
  'Boleta': 2018331201,
  'Correo': 'eguerreroc1700@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 7},
 {'id': 'inq557r',
  'Nombre': 'Nancy Fabiola Soberanes Campos',
  'Boleta': 2017330552,
  'Correo': 'nancy.fabiola03@gmail.com',
  'Carrera': 'Ing',
  'Semestre': 8},
 {'id': 'int157n',
  'Nombre': 'Carolina Villaseca Morales',
  'Boleta': 2012320931,
  'Correo': 'cvillasecam1900@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'inbrqmf',
  'Nombre': 'Mariana Yolanda Ortiz Hernández',
  'Boleta': 2014390284,
  'Correo': 'mortizh1301@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 8},
 {'id': 'in1au3a',
  'Nombre': 'Marta Patricia Castillo Velázquez ',
  'Boleta': 2020330382,
  'Correo': 'mcastillov1900@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 8},
 {'id': 'infwjvp',
  'Nombre': 'Javier Díaz Ocampo',
  'Boleta': 2016330076,
  'Correo': 'jdiazo1502@egresado.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 9},
 {'id': 'matbjql',
  'Nombre': 'Andrés Macedo Perea',
  'Boleta': 2019330052,
  'Correo': 'amacedop1801@alumno.pin.mx',
  'Carrera': 'Lic',
  'Semestre': 4},
 {'id': 'mad7xe9',
  'Nombre': 'Arturo Orlando Treviño Aguirre',
  'Boleta': 2013330395,
  'Correo': 'atrevinoa1200@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 9},
 {'id': 'madqp2p',
  'Nombre': 'Gerardo Alejandro Silva Varela',
  'Boleta': 2019330088,
  'Correo': 'gsilvav1800@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 5},
 {'id': 'max1ba4',
  'Nombre': 'Karla Magaly Hernández Hernández',
  'Boleta': 2015330364,
  'Correo': 'khernandezh1403@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 8},
 {'id': 'mafhdtd',
  'Nombre': 'Maritza Callejas Cortés',
  'Boleta': 2018330372,
  'Correo': 'mcallejasc1700@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 6},
 {'id': 'mapxaq5',
  'Nombre': 'Roberto Carlos Santos Alonzo ',
  'Boleta': 2018330621,
  'Correo': 'rsantosa1700@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 5},
 {'id': 'malzghy',
  'Nombre': 'Luis Alfonso Velázquez Martínez',
  'Boleta': 2017302871,
  'Correo': 'lvelazquezm1603@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 4},
 {'id': 'mas7wyt',
  'Nombre': 'Arturo Román Alvarado',
  'Boleta': 21083738,
  'Correo': 'aromana2100tmp@alumnoguinda.mx',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'may29ud',
  'Nombre': 'Jonás Sánchez Juárez',
  'Boleta': 2018330171,
  'Correo': 'jsanchezj1700@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 7},
 {'id': 'macncvy',
  'Nombre': 'Palacios Quiroz Pedro Italo',
  'Boleta': 21077393,
  'Correo': 'ppalaciosq1200@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'mamrllw',
  'Nombre': 'Angela Yedidya Ontiveros Yañez',
  'Boleta': 21077321,
  'Correo': 'aontiverosy1700@alumno.ipn.mx',
  'Carrera': 'Mat',
  'Semestre': 1},
 {'id': 'mahbqnw',
  'Nombre': 'Ana Karen Gómez Silvestre',
  'Boleta': 2018330182,
  'Correo': 'agomezs1705@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 6},
 {'id': 'mak375f',
  'Nombre': 'Viviana González Galván',
  'Boleta': 2016330115,
  'Correo': 'vgonzalezg1502@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 8},
 {'id': 'ma8xuae',
  'Nombre': 'Christian Mercado',
  'Boleta': 256899,
  'Correo': 'christian71291mercado@hotmail.com',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'ma21i52',
  'Nombre': 'Valeria Alejandra Rojas Alvarado',
  'Boleta': 2019340361,
  'Correo': 'vrojasa1800@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'mams8xl',
  'Nombre': 'Semiramís García de la Cruz',
  'Boleta': 2018330092,
  'Correo': 'sgarciad1700@ipn.alumno.mx',
  'Carrera': 'Ing',
  'Semestre': 7},
 {'id': 'maqr4lg',
  'Nombre': 'nayelly esmeralda neyra sampedro',
  'Boleta': 2020340339,
  'Correo': 'nneyras1900@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 1},
 {'id': 'ma5jf3d',
  'Nombre': 'Joan Emmanuel Flores Castell de Oro',
  'Boleta': 2020330326,
  'Correo': 'jfloresc1907@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 2},
 {'id': 'magp13r',
  'Nombre': 'Leonardo Ramírez Torres',
  'Boleta': 21091334,
  'Correo': 'ramireztorresleonardo12@gmail.com',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'ma1swen',
  'Nombre': 'Patricia Monserrat Antonio Allende',
  'Boleta': 2015330011,
  'Correo': 'pantonioa1400@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 4},
 {'id': 'ma5tcl8',
  'Nombre': 'Jesús Romero Alfaro',
  'Boleta': 2018330601,
  'Correo': 'jromeroa1703@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 7},
 {'id': 'mav41yd',
  'Nombre': 'Ricardo Bautista Alba ',
  'Boleta': 2020330002,
  'Correo': 'rbautistaa1600@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'maulv5t',
  'Nombre': 'Fernando Alexis Centeno Ponce',
  'Boleta': 2014081687,
  'Correo': 'alexis.centt@gmail.com',
  'Carrera': 'Ing',
  'Semestre': 5},
 {'id': 'may28wn',
  'Nombre': 'Rosas Alvarez Javier Axel',
  'Boleta': 2015050994,
  'Correo': 'jrosasa1400@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 6},
 {'id': 'maykvs2',
  'Nombre': 'Brenda Juárez López',
  'Boleta': 2020330104,
  'Correo': 'bjuarezl1600@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 2},
 {'id': 'maq6w9b',
  'Nombre': 'Aldo Calderón Ayala ',
  'Boleta': 2020330330,
  'Correo': 'acalderona1900@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'mag93m5',
  'Nombre': 'Giovanni Eboli Castro',
  'Boleta': 2016330078,
  'Correo': 'gebolic1500@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 9},
 {'id': 'masd7xp',
  'Nombre': 'Hiram Miguel Adan Cruz',
  'Boleta': 2020330365,
  'Correo': 'hadanc1900@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'mazslqh',
  'Nombre': 'Ruiz Cabrera Marco Antonio',
  'Boleta': 2020330203,
  'Correo': 'mruizc1501@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'ma6olix',
  'Nombre': 'Aldo Chilpa Casasola',
  'Boleta': 2020330022,
  'Correo': 'achilpac1600@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'mayikoi',
  'Nombre': 'Bryan Martínez López',
  'Boleta': 2019330361,
  'Correo': 'bmartinezl1501@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 4},
 {'id': 'ma581uy',
  'Nombre': 'Jesús Alejandro Díaz Guzmán',
  'Boleta': 2020330051,
  'Correo': 'jdiazg@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 2},
 {'id': 'mabgmy8',
  'Nombre': 'Gabriel Hernández López',
  'Boleta': 2015070605,
  'Correo': 'ghernandezl1401@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 7},
 {'id': 'ma5k6da',
  'Nombre': 'Fernando',
  'Boleta': 2015031124,
  'Correo': 'frodriguezg1401@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 5},
 {'id': 'malrlqb',
  'Nombre': 'Aldo Raul Salazar Benítez',
  'Boleta': 2019330212,
  'Correo': 'asalazarb1400@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'mal1uhr',
  'Nombre': 'Montserrat Gema Córdova Julián ',
  'Boleta': 2016330391,
  'Correo': 'mcordovaj1500@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 6},
 {'id': 'maxv89l',
  'Nombre': 'Jocelyn Francisco Segundo',
  'Boleta': 2016330091,
  'Correo': 'jfranciscos1500@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 7},
 {'id': 'mamczei',
  'Nombre': 'David Segundo Garcia',
  'Boleta': 2019330120,
  'Correo': 'segundogarciadavid5im13@gmail.com',
  'Carrera': 'Ing',
  'Semestre': 4},
 {'id': 'pa3mcyc',
  'Nombre': 'Mario Alfredo Sánchez Lorenzo',
  'Boleta': 2019330173,
  'Correo': 'msanchezl1500@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 5},
 {'id': 'paa4w17',
  'Nombre': 'Juan David Castillo Morales',
  'Boleta': 2016330046,
  'Correo': 'jcastillom1501@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 8},
 {'id': 'pap5yzn',
  'Nombre': 'Julio César Avila Torreblanca',
  'Boleta': 2019330006,
  'Correo': 'javilat1802@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 5},
 {'id': 'paizb1r',
  'Nombre': 'Javier Alejandro Jove Acosta ',
  'Boleta': 2015330168,
  'Correo': 'jjovea1400@alumno.ipn.com',
  'Carrera': 'Ing',
  'Semestre': 8},
 {'id': 'patprs9',
  'Nombre': 'Osbaldo Palacios',
  'Boleta': 2006330370,
  'Correo': 'jesajarostov@gmail.com',
  'Carrera': 'Lic',
  'Semestre': 7},
 {'id': 'padw3ac',
  'Nombre': 'Elliott Alvarado De Reza',
  'Boleta': 2016602542,
  'Correo': 'ealvaradod1500@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 7},
 {'id': 'pamfkkt',
  'Nombre': 'Ana Laura Hernández Ramírez',
  'Boleta': 2011330101,
  'Correo': 'ahernandezr0709@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 9},
 {'id': 'paxv9uv',
  'Nombre': 'Jesús Ricardo Martínez García ',
  'Boleta': 2020330183,
  'Correo': 'jmartinezg1612@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 2},
 {'id': 'pa4djgd',
  'Nombre': 'Eric Ortiz Pardo',
  'Boleta': 2013330349,
  'Correo': 'ecozfm@outlook.com',
  'Carrera': 'Lic',
  'Semestre': 9},
 {'id': 'pabw4ez',
  'Nombre': 'Juan Angel Soria Esparza',
  'Boleta': 21097380,
  'Correo': 'jsoriae2100tmp@alumnoguinda.mx',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'paskvv2',
  'Nombre': 'Edgar de los Santos Barajas',
  'Boleta': 2015330080,
  'Correo': 'dlsantos.edls@gmail.com',
  'Carrera': 'Ing',
  'Semestre': 9},
 {'id': 'pydnkaq',
  'Nombre': 'Cristina López Cruz',
  'Boleta': 2020330378,
  'Correo': 'clopezc1904@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'pydebta',
  'Nombre': 'Arturo Rodríguez Paredes',
  'Boleta': 21085208,
  'Correo': 'arturotitto@hotmail.com',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'pyvpb1o',
  'Nombre': 'Gilberto Ortiz Hernandez',
  'Boleta': 2012081023,
  'Correo': 'gortizh1100@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 2},
 {'id': 'pytbzfr',
  'Nombre': 'MANUEL ALEJANDRO SÁNCHEZ CASTREJÓN',
  'Boleta': 21083387,
  'Correo': 'msanchezc1607@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'pyuyo1e',
  'Nombre': 'Jorge Julián Traspaderne Quintero',
  'Boleta': 2020330272,
  'Correo': 'jtraspaderneq1600@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'pywx4k6',
  'Nombre': 'Mario Fernando Badillo Iglesias',
  'Boleta': 21005049,
  'Correo': 'mbadilloi1700@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 1},
 {'id': 'py95w64',
  'Nombre': 'Laura Itzel Álvarez Osornio',
  'Boleta': 2019310119,
  'Correo': 'lalvarezo1800@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'pyx8y56',
  'Nombre': 'Dulce Pacheco Andrade',
  'Boleta': 2011330171,
  'Correo': 'dulce.julliet@gmail.com',
  'Carrera': 'Ing',
  'Semestre': 2},
 {'id': 'pyx8o9y',
  'Nombre': 'Valeria Benítez Alcántara ',
  'Boleta': 2016340161,
  'Correo': 'vbeniteza1500@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 2},
 {'id': 'pya3f1h',
  'Nombre': 'Rodrigo Bautista Castillo',
  'Boleta': 21007826,
  'Correo': 'rbautistac1700@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'py2pzvh',
  'Nombre': 'ELSA LETICIA ARCOS DIAZ ',
  'Boleta': 190630,
  'Correo': 'earcosd0700@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'pyhzfvz',
  'Nombre': 'Fernando Ángel García Mandujano',
  'Boleta': 2016330099,
  'Correo': 'fgarciam1503@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 2},
 {'id': 'pyiyocr',
  'Nombre': 'Gilberto Reza Cortés',
  'Boleta': 21086803,
  'Correo': 'recor_g@outlook.com',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'pyswzmn',
  'Nombre': 'Ingrid Sayuri Mota de la Rosa',
  'Boleta': 2020330396,
  'Correo': 'imotad1900@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'pyjmwm6',
  'Nombre': 'Elena Altair Pozas Ramirez',
  'Boleta': 2020330206,
  'Correo': 'epozasr1600@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 2},
 {'id': 'pyi27la',
  'Nombre': 'Mauricio Mejia Velazquez',
  'Boleta': 2017601531,
  'Correo': 'rayomejia@outllok.es',
  'Carrera': 'Ing',
  'Semestre': 1},
 {'id': 'pywg4ou',
  'Nombre': 'María Azul Plascencia Cano',
  'Boleta': 2020330407,
  'Correo': 'mplascenciac1900@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 2},
 {'id': 'pyxi1bs',
  'Nombre': 'Rojas Perez Jessica Itzel',
  'Boleta': 2020340039,
  'Correo': 'jrojasp1500@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 1},
 {'id': 'pyyrf93',
  'Nombre': 'Miguel Durán Ramírez',
  'Boleta': 2020330048,
  'Correo': 'mduranr1600@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 2},
 {'id': 'pyzu8mo',
  'Nombre': 'César Alejandro González García',
  'Boleta': 2020330417,
  'Correo': 'cgonzalezg1905@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 1},
 {'id': 'pyfu6j7',
  'Nombre': 'Hernández Martínez Pricila ',
  'Boleta': 2018603002,
  'Correo': 'phernandezm1702@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'py2xql2',
  'Nombre': 'Brayan Ríos Escobar ',
  'Boleta': 21089897,
  'Correo': 'brayan_rios_escobar@hotmail.com',
  'Carrera': 'Mat',
  'Semestre': 1},
 {'id': 'pyw46z7',
  'Nombre': 'David Omar Lazcano Godinez',
  'Boleta': 21051733,
  'Correo': 'david_omar06@hotmail.com',
  'Carrera': 'Ing',
  'Semestre': 1},
 {'id': 'pyiyzz4',
  'Nombre': 'Atzin Metzeri Díaz Zarco',
  'Boleta': 2010140392,
  'Correo': 'am_dz@outlook.com',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'py6j321',
  'Nombre': 'Luis Andrik Mahonri Perez Flores',
  'Boleta': 2020330334,
  'Correo': 'lperezf1901@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 2},
 {'id': 'pyt2ula',
  'Nombre': 'Zahib Gamaliel Ventura Fernández',
  'Boleta': 2020330337,
  'Correo': 'zventuraf1900@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'pyi6sfx',
  'Nombre': 'Sara Ithamar López Martínez',
  'Boleta': 2021330016,
  'Correo': 'slopezm2002@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 1},
 {'id': 'pyleu8d',
  'Nombre': 'Díaz Tello Claudia Brigitte ',
  'Boleta': 2020330061,
  'Correo': 'cdiazt1900@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'pylicjd',
  'Nombre': 'Mauricio Hernández Castañeda ',
  'Boleta': 2020330333,
  'Correo': 'mhernandezc1917@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 2},
 {'id': 'pyhddke',
  'Nombre': 'Carolina Águila Contreras',
  'Boleta': 2020330017,
  'Correo': 'caguilac1600@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'pyjnz4h',
  'Nombre': 'Flores Valente Christhian',
  'Boleta': 21022220,
  'Correo': 'cfloresv1700@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'py7v5w9',
  'Nombre': 'Córdova Mejía Everardo Fabián',
  'Boleta': 2013090636,
  'Correo': 'ecordovam1200@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 5},
 {'id': 'pyz4jq3',
  'Nombre': 'Ian Jared Canales Hernández',
  'Boleta': 2013070501,
  'Correo': 'icanalesh2100tmp@alumnoguinda.mx',
  'Carrera': 'Ing',
  'Semestre': 4},
 {'id': 'pyk88fv',
  'Nombre': 'Aguilar Sánchez Carlos Adrian',
  'Boleta': 2016330008,
  'Correo': 'carlos_ass_97@hotmail.com',
  'Carrera': 'Lic',
  'Semestre': 4},
 {'id': 'pyhheai',
  'Nombre': 'Daniela Ocampo Salgado',
  'Boleta': 2018330322,
  'Correo': 'docampos1700@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 6},
 {'id': 'py2797l',
  'Nombre': 'Saúl Guzmán Coca',
  'Boleta': 2019330166,
  'Correo': 'sguzmanc1500@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 5},
 {'id': 'py73a29',
  'Nombre': 'Zaa Emmanuel Soto Hernández ',
  'Boleta': 2015090743,
  'Correo': 'zsotoh1400@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 7},
 {'id': 'pyiluhe',
  'Nombre': 'Candy Ivonne Palomares Martínez',
  'Boleta': 2016301255,
  'Correo': 'cpalomaresm1500@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 5},
 {'id': 'pyn67al',
  'Nombre': 'Gabriel Antonio Fernández Galicia',
  'Boleta': 2019330103,
  'Correo': 'gfernandezg1800@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 5},
 {'id': 'pyhl66u',
  'Nombre': 'Paola marquez garcia',
  'Boleta': 2010330209,
  'Correo': 'paolamar414@gmail.com',
  'Carrera': 'Lic',
  'Semestre': 6},
 {'id': 'pybngt4',
  'Nombre': 'Liliana García Ochoa ',
  'Boleta': 2014330090,
  'Correo': 'Lilybaby-4@hotmail.com',
  'Carrera': 'Ing',
  'Semestre': 8},
 {'id': 'pyvn87t',
  'Nombre': 'André Paolo Beverido Gómez',
  'Boleta': 2019330390,
  'Correo': 'abeveridog1800@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 5},
 {'id': 'pyp1wtm',
  'Nombre': 'Milton Yamil Velazquez Montoya',
  'Boleta': 2019330095,
  'Correo': 'mvelazquezm1400@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 5},
 {'id': 'pyy2c17',
  'Nombre': 'Mariana Muñoz Bernal ',
  'Boleta': 2017330402,
  'Correo': 'mmunozb1601@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 8},
 {'id': 'py8nwxx',
  'Nombre': 'Muriel Sánchez Balderas',
  'Boleta': 2017330542,
  'Correo': 'msanchezb1602@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 8},
 {'id': 'pyvb4g5',
  'Nombre': 'Mauricio Gutiérrez Gutiérrez',
  'Boleta': 2015300137,
  'Correo': 'mauryx12@gmail.com',
  'Carrera': 'Lic',
  'Semestre': 4},
 {'id': 'pyoh3u8',
  'Nombre': 'Hershel Brandon Luna Miranda',
  'Boleta': 2018330691,
  'Correo': 'hlunam1700@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 4},
 {'id': 'py7edqz',
  'Nombre': 'Ernesto Claire Murillo ',
  'Boleta': 2017330301,
  'Correo': 'Eclairem1600@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 8},
 {'id': 'pyri239',
  'Nombre': 'Carlos Esteban Higuera Méndez',
  'Boleta': 2019330046,
  'Correo': 'chigueram1800@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 4},
 {'id': 'pyurk4r',
  'Nombre': 'Jesús Estrada Hernández',
  'Boleta': 2010330341,
  'Correo': 'estradaesfm@gmail.com',
  'Carrera': 'Lic',
  'Semestre': 8},
 {'id': 'pydq5uv',
  'Nombre': 'Issac Vega López',
  'Boleta': 2016330330,
  'Correo': 'ivegal1200@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 8},
 {'id': 'pyslydy',
  'Nombre': 'Diego Rodrigo Uribe Rodríguez',
  'Boleta': 2016330390,
  'Correo': 'di5g0ur1be@gmail.com',
  'Carrera': 'Lic',
  'Semestre': 7},
 {'id': 'pya7bnr',
  'Nombre': 'Ana laura Alvarez',
  'Boleta': 2014330008,
  'Correo': 'lauraalvarezconte@gmail.com',
  'Carrera': 'Lic',
  'Semestre': 8},
 {'id': 'pypnux5',
  'Nombre': 'Cruz Javier García Hernández ',
  'Boleta': 2019410084,
  'Correo': 'cgarcia1802@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 5},
 {'id': 'pytdlka',
  'Nombre': 'Angel Uriel Cristobal Salas ',
  'Boleta': 2018331531,
  'Correo': 'acristobalsal1700@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 5},
 {'id': 'pyw9e8b',
  'Nombre': 'Bibiana Guadalupe Campos Rodea',
  'Boleta': 2018330212,
  'Correo': 'bcamposr1700@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 6},
 {'id': 'pymlvvi',
  'Nombre': 'Néstor de Jesús Mosqueda Macías ',
  'Boleta': 2018330901,
  'Correo': 'nmosquedam1700@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 6},
 {'id': 'pyfabfg',
  'Nombre': 'Andrea Paola Martínez Cortés ',
  'Boleta': 2015330192,
  'Correo': 'amartinezc1411@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 4},
 {'id': 'pycmdzp',
  'Nombre': 'Carlos Magaña',
  'Boleta': 2004330148,
  'Correo': 'carmalo221@gmail.com',
  'Carrera': 'Ing',
  'Semestre': 8},
 {'id': 'py2z11a',
  'Nombre': 'Gerardo Alan Gutiérrez González',
  'Boleta': 2012130513,
  'Correo': 'ggutierrezg1703@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 4},
 {'id': 'pyhnwxm',
  'Nombre': 'Pedro Soria Ahuatzin',
  'Boleta': 2014011115,
  'Correo': 'psoriaa1300@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 8},
 {'id': 'pyllqyz',
  'Nombre': 'Miriam Andrea Pérez Hernández ',
  'Boleta': 2015101699,
  'Correo': 'mperezh1400@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 5},
 {'id': 'pyjrqcg',
  'Nombre': 'Marco Antonio Cano Márquez ',
  'Boleta': 2017330241,
  'Correo': 'mcanom1600@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 7},
 {'id': 'py5swry',
  'Nombre': 'Alejandro Hernandez Pineda',
  'Boleta': 2015330153,
  'Correo': 'ahernandezp1407@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 8},
 {'id': 'pyupej7',
  'Nombre': 'Jesus Godinez Reyna',
  'Boleta': 2018331561,
  'Correo': 'jgodinezr0900@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 2},
 {'id': 'py6ao75',
  'Nombre': 'Perla Itzel López Ramírez ',
  'Boleta': 2018330662,
  'Correo': 'plopezr1700@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'pygsqaq',
  'Nombre': 'Oscar Alejandro Hernández Aguilar',
  'Boleta': 2019330381,
  'Correo': 'ohernandeza1802@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 2},
 {'id': 'pysoakc',
  'Nombre': 'Oscar Andres Valencia Magaña',
  'Boleta': 21103560,
  'Correo': 'ovalenciam1701@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'pybem7f',
  'Nombre': 'Enriquez Gutierrez Erick David',
  'Boleta': 2020640120,
  'Correo': 'eenriquezg1600@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 2},
 {'id': 'pyvwb8j',
  'Nombre': 'Maiky Hernández Flores',
  'Boleta': 21045479,
  'Correo': 'mhernadezf1700@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'pyka4v1',
  'Nombre': 'Isaac Sánchez Aboytes',
  'Boleta': 21093042,
  'Correo': 'isancheza2100tmp@alumnoguinda.mx',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'pyg4bda',
  'Nombre': 'Gonzalo Flores García',
  'Boleta': 2020330049,
  'Correo': 'gfloresg1603@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'pycuah1',
  'Nombre': 'César González Montiel',
  'Boleta': 21033639,
  'Correo': 'cesarkei23@gmail.com',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'pygmizq',
  'Nombre': 'Britany Jaentt Poumian Oseguera ',
  'Boleta': 2020330335,
  'Correo': 'bpoumiano1400@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'py5xoco',
  'Nombre': 'JOSE MANUEL GONZALEZ DE SANTIAGO',
  'Boleta': 21032527,
  'Correo': 'manuel_glezds@hotmail.com',
  'Carrera': 'Ing',
  'Semestre': 1},
 {'id': 'py6q6vj',
  'Nombre': 'Arturo Romero Palacios',
  'Boleta': 21083186,
  'Correo': 'aromerop2101tmp@alumnoguinda.mx',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'pyt5gt1',
  'Nombre': 'Elvira Susana Hernandez Cuevas',
  'Boleta': 2014030605,
  'Correo': 'ehernandezc1301@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 2},
 {'id': 'pyp5gji',
  'Nombre': 'Cesia Sunem Barrera Bahena',
  'Boleta': 2018390942,
  'Correo': 'cbarrerab1700@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'pypkqpu',
  'Nombre': 'Cecilia Viridiana García Martín',
  'Boleta': 21040814,
  'Correo': 'garcia0216.viri@gmail.com',
  'Carrera': 'Ing',
  'Semestre': 1},
 {'id': 'pyz55y2',
  'Nombre': 'Luis Gustavo Urbano Jimenez',
  'Boleta': 2020330368,
  'Correo': 'lurbanoj1900@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'pyp3gsu',
  'Nombre': 'Angel Amado Jiménez',
  'Boleta': 21003481,
  'Correo': 'misterpolla13@gmail.com',
  'Carrera': 'Ing',
  'Semestre': 1},
 {'id': 'py4o5j8',
  'Nombre': 'Emma Laura Rivera Pen',
  'Boleta': 2017330502,
  'Correo': 'eriverap1603@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'pyjg9c1',
  'Nombre': 'Ángel David Lazcano Roberto',
  'Boleta': 2018330541,
  'Correo': 'alazcanor1700@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 3},
 {'id': 'pycj723',
  'Nombre': 'Francisco Daniel López Campillo',
  'Boleta': 21046876,
  'Correo': 'flopezc2100tmp@alumnoguinda.mx',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'pyrggxd',
  'Nombre': 'Aleph Alberto',
  'Boleta': 2020330052,
  'Correo': 'alephescobar@live.com.mx',
  'Carrera': 'Lic',
  'Semestre': 2},
 {'id': 'pyan482',
  'Nombre': 'Rocio Angélica Pérez Garduño ',
  'Boleta': 2020330405,
  'Correo': 'rperezg1901@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 2},
 {'id': 'py8pow9',
  'Nombre': 'Isidoro Hernández Jonathan ',
  'Boleta': 2020340418,
  'Correo': 'jisidoroh1900@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'pyijpxy',
  'Nombre': 'Diego Dávila Arellano',
  'Boleta': 2021330075,
  'Correo': 'ddavilaa2000@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'pyp2uub',
  'Nombre': 'Ricardo Keni Arredondo Ángeles',
  'Boleta': 2012330014,
  'Correo': 'jojo.kenee@gmail.com',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'pys568g',
  'Nombre': 'Axel Uriel Padilla Amezcua',
  'Boleta': 21078969,
  'Correo': 'apadillaa1700@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'pynt6vd',
  'Nombre': 'Iván Eduardo Becerra Torres',
  'Boleta': 2019340086,
  'Correo': 'ibecerrat1800@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 3},
 {'id': 'pyatbiv',
  'Nombre': 'Mauricio León González ',
  'Boleta': 21048468,
  'Correo': 'mleong1602@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'pytx79i',
  'Nombre': 'Roberto Corona Morales ',
  'Boleta': 2020330409,
  'Correo': 'rcoronam1900@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 1},
 {'id': 'pykcqjb',
  'Nombre': 'Brandon Cerón Vega ',
  'Boleta': 2016350097,
  'Correo': 'bceronv1500@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 8},
 {'id': 'pyebh1o',
  'Nombre': 'Eduardo Germán De la Torre Quintana',
  'Boleta': 2016330075,
  'Correo': 'edelatorreq1500@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 6},
 {'id': 'pyfbl2m',
  'Nombre': 'Mauricio Chávez Sánchez',
  'Boleta': 2013330165,
  'Correo': 'm.cs.aperrier@gmail.com',
  'Carrera': 'Lic',
  'Semestre': 5},
 {'id': 'pytgued',
  'Nombre': 'Ruiz Ramos Andres',
  'Boleta': 2015330380,
  'Correo': 'aruizr1402@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 7},
 {'id': 'pywccdh',
  'Nombre': 'Jorge Francisco caballero Gutiérrez',
  'Boleta': 2018351541,
  'Correo': 'jcaballerog1700@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 4},
 {'id': 'pyzfwor',
  'Nombre': 'Carranza Gómez Luis Alberto ',
  'Boleta': 2019330400,
  'Correo': 'lcarranzag1400@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 4},
 {'id': 'pyxwmbp',
  'Nombre': 'Alexis Martínez Arredondo',
  'Boleta': 2019330122,
  'Correo': 'amartineza1504@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 4},
 {'id': 'pyt6fta',
  'Nombre': 'Juan Jesús Santillan Delgadillo',
  'Boleta': 2018330811,
  'Correo': 'jsantilland1700@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 6},
 {'id': 'pygvdg3',
  'Nombre': 'Leonardo Juárez Gallegos',
  'Boleta': 2015330169,
  'Correo': 'ljuarezg1401@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 5},
 {'id': 'py6lj32',
  'Nombre': 'Carlos Alejandro reyes torres ',
  'Boleta': 2015050753,
  'Correo': 'creyest1400@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 5},
 {'id': 'pyilgnw',
  'Nombre': 'Gloria Sarahi Martinez Rodea ',
  'Boleta': 2015030788,
  'Correo': 'gmartinezr1404@ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 7},
 {'id': 'py9kwlj',
  'Nombre': 'Aarón Yáñez Armenta',
  'Boleta': 2018331031,
  'Correo': 'ayaneza1700@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 7},
 {'id': 'py7bis3',
  'Nombre': 'Díaz Barrera Erick Rubén',
  'Boleta': 2013031297,
  'Correo': 'ediazb1200@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 5},
 {'id': 'pyyiqm3',
  'Nombre': 'Fernando Hernández Martínez',
  'Boleta': 2015020621,
  'Correo': 'fernandohdzmtz123@gmail.com',
  'Carrera': 'Ing',
  'Semestre': 6},
 {'id': 'pywt5m7',
  'Nombre': 'JUAN JOSE SOTO ZAMORA',
  'Boleta': 205330190,
  'Correo': 'dredreico.jose@gmail.com',
  'Carrera': 'Ing',
  'Semestre': 8},
 {'id': 'pymnhx2',
  'Nombre': 'Laura Aline Gómez Gómez ',
  'Boleta': 2013330314,
  'Correo': 'lgomezg1202@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 8},
 {'id': 'pymdcbk',
  'Nombre': 'Miriam Betzabeth Rodríguez Castelán',
  'Boleta': 2018330422,
  'Correo': 'mrodriguezc1703@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 7},
 {'id': 'py7p3tn',
  'Nombre': 'Alfredo Morales Rojas',
  'Boleta': 2019330117,
  'Correo': 'amoralesr1500@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 5},
 {'id': 'py5u5i6',
  'Nombre': 'MAX EDGAR',
  'Boleta': 2008330385,
  'Correo': 'maxedgarmoreno@gmail.com',
  'Carrera': 'Ing',
  'Semestre': 7},
 {'id': 'pyfzh82',
  'Nombre': 'Ricardo Miguel Cervantes Luna',
  'Boleta': 2016330053,
  'Correo': 'ricardoatari@gmail.com',
  'Carrera': 'Ing',
  'Semestre': 6},
 {'id': 'pyuls95',
  'Nombre': 'Diana Méndez Avilés ',
  'Boleta': 2019330260,
  'Correo': 'dmendeza1500@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 5},
 {'id': 'pyd25lf',
  'Nombre': 'Gustavo Adolfo Sánchez Acevedo ',
  'Boleta': 2015071295,
  'Correo': 'gsancheza1401@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 5},
 {'id': 'pyhm18r',
  'Nombre': 'Atzhiry Selene Montaño Ochoa',
  'Boleta': 2018330602,
  'Correo': 'amontanoo1700@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 7},
 {'id': 'pyljvg3',
  'Nombre': 'Perez Martinez Cesar Oldair',
  'Boleta': 2018331121,
  'Correo': 'cperezm1705@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 6},
 {'id': 'py6ec56',
  'Nombre': 'Kevin Samuel Bernal Fuentes',
  'Boleta': 2019330161,
  'Correo': 'kbernalf1500@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 5},
 {'id': 'py35gf6',
  'Nombre': 'Luis Alberto Aldana Villalobos',
  'Boleta': 2016330012,
  'Correo': 'laldanav1500@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 7},
 {'id': 'pyc8wsx',
  'Nombre': 'Deina Guadalupe Hernández Chávez',
  'Boleta': 2018330552,
  'Correo': 'sheremia_15@hotmail.com',
  'Carrera': 'Ing',
  'Semestre': 4},
 {'id': 'pys7c2z',
  'Nombre': 'Ximena Sánchez Sumano',
  'Boleta': 2018330412,
  'Correo': 'xsanchezs1700@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 6},
 {'id': 'py1ssyu',
  'Nombre': 'Aarón Camargo Trejo',
  'Boleta': 2018330951,
  'Correo': 'acamargot1700@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 7},
 {'id': 'pyb49dq',
  'Nombre': 'José Joaquín Morales Cabrera',
  'Boleta': 2019330330,
  'Correo': 'jmoralesc1502@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 5},
 {'id': 'pyk847q',
  'Nombre': 'Erick Martinez Barbosa',
  'Boleta': 2014330173,
  'Correo': 'emartinezb0904@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 4},
 {'id': 'pysm2sn',
  'Nombre': 'Alejandro Monroy Azpeitia',
  'Boleta': 2019330061,
  'Correo': 'amonroya1800@alumno.ipn.mx',
  'Carrera': 'Lic',
  'Semestre': 4},
 {'id': 'pyykrcs',
  'Nombre': 'Tamara Rodríguez Solis',
  'Boleta': 2018330362,
  'Correo': 'trodriguezs1700@alumno.ipn.mx',
  'Carrera': 'Ing',
  'Semestre': 6}]