def dicti():
   return {2020330061: {'Nombre': 'Díaz Tello Claudia Brigitte',
  'Id': 'pyleu8d',
  'Curso': ['Python From Zero to Hero'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2020330061},
 2021330016: {'Nombre': 'Sara Ithamar López Martínez',
  'Id': 'pyi6sfx',
  'Curso': ['Python From Zero to Hero'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2021330016},
 21085208: {'Nombre': 'Arturo Rodríguez Paredes',
  'Id': 'pydebta',
  'Curso': ['Python From Zero to Hero'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 21085208},
 2019330061: {'Nombre': 'Alejandro Monroy Azpeitia',
  'Id': 'pysm2sn',
  'Curso': ['Python From Zero to Hero'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2019330061},
 2020330396: {'Nombre': 'Ingrid Sayuri Mota de la Rosa',
  'Id': 'pyswzmn',
  'Curso': ['Python From Zero to Hero'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2020330396},
 2020330049: {'Nombre': 'Gonzalo Flores García',
  'Id': 'pyg4bda',
  'Curso': ['Python From Zero to Hero'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2020330049},
 2018330602: {'Nombre': 'Atzhiry Selene Montaño Ochoa',
  'Id': 'pyhm18r',
  'Curso': ['Python From Zero to Hero'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2018330602},
 2018330422: {'Nombre': 'Miriam Betzabeth Rodríguez Castelán',
  'Id': 'pymdcbk',
  'Curso': ['Python From Zero to Hero'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2018330422},
 2019330161: {'Nombre': 'Kevin Samuel Bernal Fuentes',
  'Id': 'py6ec56',
  'Curso': ['Python From Zero to Hero'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2019330161},
 21083186: {'Nombre': 'Arturo Romero Palacios',
  'Id': 'py6q6vj',
  'Curso': ['Python From Zero to Hero'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 21083186},
 2010330341: {'Nombre': 'Jesús Estrada Hernández',
  'Id': 'pyurk4r',
  'Curso': ['Python From Zero to Hero'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2010330341},
 2015101699: {'Nombre': 'Miriam Andrea Pérez Hernández',
  'Id': 'pyllqyz',
  'Curso': ['Python From Zero to Hero'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2015101699},
 2021330075: {'Nombre': 'Diego Dávila Arellano',
  'Id': 'pyijpxy',
  'Curso': ['Python From Zero to Hero'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2021330075},
 2019330360: {'Nombre': 'Rodrigo Torres Castillo',
  'Id': 'in5dx3x',
  'Curso': ['Ingeniería de Datos'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2019330360},
 2014601112: {'Nombre': 'Katia Michel Martinez Rios',
  'Id': 'in69jje',
  'Curso': ['Ingeniería de Datos'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2014601112},
 2018331201: {'Nombre': 'Erwin Eduardo Guerrero Cazares',
  'Id': 'iny7mz5',
  'Curso': ['Ingeniería de Datos'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2018331201},
 2013330349: {'Nombre': 'Eric Ortiz Pardo',
  'Id': 'pa4djgd',
  'Curso': ['Pandas para Ciencia de Datos'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2013330349},
 2015330080: {'Nombre': 'Edgar de los Santos Barajas',
  'Id': 'paskvv2',
  'Curso': ['Pandas para Ciencia de Datos'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2015330080},
 2020330183: {'Nombre': 'Jesús Ricardo Martínez García',
  'Id': 'paxv9uv',
  'Curso': ['Pandas para Ciencia de Datos'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2020330183},
 2020330309: {'Nombre': 'Rodolfo Carlos Lagunas Jardines',
  'Id': 'in1ui2w',
  'Curso': ['Pandas para Ciencia de Datos'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2020330309},
 2019330212: {'Nombre': 'Aldo Raúl Salazar Benítez',
  'Id': 'malrlqb',
  'Curso': ['Matlab'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2019330212},
 2019330052: {'Nombre': 'Andrés Macedo Perea',
  'Id': 'matbjql',
  'Curso': ['Matlab'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2019330052},
 2013330395: {'Nombre': 'Arturo Orlando Treviño Aguirre',
  'Id': 'mad7xe9',
  'Curso': ['Matlab'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2013330395},
 2019330361: {'Nombre': 'Bryan Martínez López',
  'Id': 'mayikoi',
  'Curso': ['Matlab'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2019330361},
 2016330091: {'Nombre': 'Jocelyn Francisco Segundo',
  'Id': 'maxv89l',
  'Curso': ['Matlab'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2016330091},
 2018330171: {'Nombre': 'Jonás Sánchez Juárez',
  'Id': 'may29ud',
  'Curso': ['Matlab'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2018330171},
 2019330088: {'Nombre': 'Gerardo Alejandro Silva Varela',
  'Id': 'madqp2p',
  'Curso': ['Matlab'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2019330088},
 2016330391: {'Nombre': 'Montserrat Gema Córdova Julián',
  'Id': 'mal1uhr',
  'Curso': ['Matlab'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2016330391},
 2020330330: {'Nombre': 'Aldo Calderón Ayala',
  'Id': 'maq6w9b',
  'Curso': ['Matlab'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2020330330},
 2020330104: {'Nombre': 'Brenda Juárez López',
  'Id': 'maykvs2',
  'Curso': ['Matlab'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2020330104},
 2015031124: {'Nombre': 'Fernando Rodríguez García',
  'Id': 'ma5k6da',
  'Curso': ['Matlab'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2015031124},
 2020340339: {'Nombre': 'Nayelly Esmeralda Neyra Sampedro',
  'Id': 'maqr4lg',
  'Curso': ['Matlab'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2020340339},
 2018330092: {'Nombre': 'Semiramis García De La Cruz',
  'Id': 'mams8xl',
  'Curso': ['Matlab'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211,
  'Boleta': 2018330092},
 2018331121: {'Nombre': 'Perez Martinez Cesar Oldair ',
  'Id': 'pyljvg3',
  'Curso': ['Python From Zero to Hero'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211},
  2020330046:{'Nombre': 'Antonio Elías Vargas ',
  'Id': 'ineids2',
  'Curso': ['Pandas para Ciencia de Datos', 'Ingeniería de Datos'],
  'Fecha': 'Febrero del 2021',
  'Periodo': 20211}}

def images():
    return {'pyleu8d0': {'url': 'https://i.ibb.co/6WyB9Vq/Constancia-D-az-Tello.jpg',
  'curso': 'Python From Zero to Hero',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Díaz Tello Claudia Brigitte'},
  "ineids20":{"url":"https://i.ibb.co/MpsL502/Constancia-El-as-Vargas-1.jpg",
                        "curso":"Ingeniería de Datos",
                        "Fecha": "Febrero del 2021",
                        "Nombre": "Antonio Elias Vargas",
                        },
            "ineids21":{"url":"https://i.ibb.co/ZdBRm5X/Constancia-El-as-Vargas-2.jpg",
                        "curso":"Pandas para Ciencia de Datos",
                        "Fecha": "Febrero del 2021",
                        "Nombre": "Antonio Elias Vargas"
                        },
 'pyi6sfx0': {'url': 'https://i.ibb.co/NnKwjvm/Constancia-L-pez-Mart-nez.jpg',
  'curso': 'Python From Zero to Hero',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Sara Ithamar López Martínez'},
 'pydebta0': {'url': 'https://i.ibb.co/DkZ0PTV/Constancia-Rodr-guez-Paredes.jpg',
  'curso': 'Python From Zero to Hero',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Arturo Rodríguez Paredes'},
 'pysm2sn0': {'url': 'https://i.ibb.co/Rh93dQ4/Constancia-Monroy-Azpeitia.jpg',
  'curso': 'Python From Zero to Hero',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Alejandro Monroy Azpeitia'},
 'pyswzmn0': {'url': 'https://i.ibb.co/XWCtXVw/Constancia-Mota-de-la-Rosa.jpg',
  'curso': 'Python From Zero to Hero',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Ingrid Sayuri Mota de la Rosa'},
 'pyg4bda0': {'url': 'https://i.ibb.co/Lnj5SnR/Constancia-Flores-Garc-a.jpg',
  'curso': 'Python From Zero to Hero',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Gonzalo Flores García'},
 'pyhm18r0': {'url': 'https://i.ibb.co/8c85zNr/Constancia-Monta-o-Ochoa.jpg',
  'curso': 'Python From Zero to Hero',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Atzhiry Selene Montaño Ochoa'},
 'pymdcbk0': {'url': 'https://i.ibb.co/0DxbyLq/Constancia-Rodr-guez-Castel-n.jpg',
  'curso': 'Python From Zero to Hero',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Miriam Betzabeth Rodríguez Castelán'},
 'py6ec560': {'url': 'https://i.ibb.co/qxSbxKN/Constancia-Bernal-Fuentes.jpg',
  'curso': 'Python From Zero to Hero',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Kevin Samuel Bernal Fuentes'},
 'py6q6vj0': {'url': 'https://i.ibb.co/8X8SBTq/Constancia-Romero-Palacios.jpg',
  'curso': 'Python From Zero to Hero',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Arturo Romero Palacios'},
 'pyurk4r0': {'url': 'https://i.ibb.co/dW5Tn7K/Constancia-Estrada-Hern-ndez.jpg',
  'curso': 'Python From Zero to Hero',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Jesús Estrada Hernández'},
 'pyllqyz0': {'url': 'https://i.ibb.co/RhgkBjF/Constancia-P-rez-Hern-ndez.jpg',
  'curso': 'Python From Zero to Hero',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Miriam Andrea Pérez Hernández'},
 'pyijpxy0': {'url': 'https://i.ibb.co/BKy9CR8/Constancia-D-vila-Arellano.jpg',
  'curso': 'Python From Zero to Hero',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Diego Dávila Arellano'},
 'in5dx3x0': {'url': 'https://i.ibb.co/h8Y93f9/Constancia-Torres-Castillo.jpg',
  'curso': 'Ingeniería de Datos',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Rodrigo Torres Castillo'},
 'in69jje0': {'url': 'https://i.ibb.co/BP7Ky2d/Constancia-Mart-nez-R-os.jpg',
  'curso': 'Ingeniería de Datos',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Katia Michel Martinez Rios'},
 'iny7mz50': {'url': 'https://i.ibb.co/TKCtYL7/Constancia-Guerrero-Cazares.jpg',
  'curso': 'Ingeniería de Datos',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Erwin Eduardo Guerrero Cazares'},
 'pa4djgd0': {'url': 'https://i.ibb.co/Kr2mxzN/Constancia-Ortiz-Pardo.jpg',
  'curso': 'Pandas para Ciencia de Datos',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Eric Ortiz Pardo'},
 'paskvv20': {'url': 'https://i.ibb.co/TKtjqNq/Constancia-de-los-Santos-Barajas.jpg',
  'curso': 'Pandas para Ciencia de Datos',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Edgar de los Santos Barajas'},
 'paxv9uv0': {'url': 'https://i.ibb.co/wrLzfxD/Constancia-Mart-nez-Garc-a.jpg',
  'curso': 'Pandas para Ciencia de Datos',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Jesús Ricardo Martínez García'},
 'in1ui2w0': {'url': 'https://i.ibb.co/J5HXwtx/Constancia-Lagunas-Jardines-1.jpg',
  'curso': 'Pandas para Ciencia de Datos',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Rodolfo Carlos Lagunas Jardines'},
 'malrlqb0': {'url': 'https://i.ibb.co/H2sYt92/Constancia-Salazar-Ben-tez.jpg',
  'curso': 'Matlab',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Aldo Raúl Salazar Benítez'},
 'matbjql0': {'url': 'https://i.ibb.co/3drLW6z/Constancia-Macedo-Perea.jpg',
  'curso': 'Matlab',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Andrés Macedo Perea'},
 'mad7xe90': {'url': 'https://i.ibb.co/HGLz0mV/Constancia-Trevi-o-Aguirre.jpg',
  'curso': 'Matlab',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Arturo Orlando Treviño Aguirre'},
 'mayikoi0': {'url': 'https://i.ibb.co/vYhSMhg/Constancia-Cardona-L-pez-1.jpg',
  'curso': 'Matlab',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Bryan Martínez López'},
 'maxv89l0': {'url': 'https://i.ibb.co/4FhHtB6/Constancia-Francisco-Segundo.jpg',
  'curso': 'Matlab',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Jocelyn Francisco Segundo'},
 'may29ud0': {'url': 'https://i.ibb.co/kym8dPr/Constancia-Ju-rez-L-pez.jpg',
  'curso': 'Matlab',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Jonás Sánchez Juárez'},
 'madqp2p0': {'url': 'https://i.ibb.co/Dg5sVmV/Constancia-Silva-Varela.jpg',
  'curso': 'Matlab',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Gerardo Alejandro Silva Varela'},
 'mal1uhr0': {'url': 'https://i.ibb.co/s66fHxy/Constancia-C-rdova-Juli-n.jpg',
  'curso': 'Matlab',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Montserrat Gema Córdova Julián'},
 'maq6w9b0': {'url': 'https://i.ibb.co/njLNZWJ/Constancia-Calder-n-Ayala.jpg',
  'curso': 'Matlab',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Aldo Calderón Ayala'},
 'maykvs20': {'url': 'https://i.ibb.co/vYhSMhg/Constancia-Cardona-L-pez-1.jpg',
  'curso': 'Matlab',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Brenda Juárez López'},
 'ma5k6da0': {'url': 'https://i.ibb.co/Lnj5SnR/Constancia-Flores-Garc-a.jpg',
  'curso': 'Matlab',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Fernando Rodríguez García'},
 'maqr4lg0': {'url': 'https://i.ibb.co/3CS0Wfy/Constancia-Neyra-Sampedro.jpg',
  'curso': 'Matlab',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Nayelly Esmeralda Neyra Sampedro'},
 'mams8xl0': {'url': 'https://i.ibb.co/LkP7qRt/Constancia-Garc-a-de-la-Cruz.jpg',
  'curso': 'Matlab',
  'Fecha': 'Febrero del 2021',
  'Nombre': 'Semiramis García De La Cruz'}}
 